### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by StaffanBetner** [ScilifelabDataCentre/covid-portal#1065]
Hej! Får 404 Not Found på t.ex. https://www.pathogens.se/ och https://www.covid19dataportal.se/

Certifikaten verkar ha gått ut också?

**Comment by LianeHughes** [comment]
Hej,
Tack för att du kontaktade oss.
Vi har för närvarande problem med vårt kluster. Vårt team arbetar för att lösa detta så snabbt som möjligt. Portalen kan hittas https://pathogens.se

Hello,

Thank you for reaching out. We are currently experiencing issues with one of our clusters. The team are working to fix this as quickly as possibly. For now, the Portal is available at: https://pathogens.se
