### ISSUE TITLE
Set up a dev server to host site for viewing and debug

### ISSUE THREAD

**Issue by pekrau** [ScilifelabDataCentre/covid-portal#14]
We need a dev server to see what it will look like. It should set up so that `git pull` will get the master stuff from here.

**Comment by talavis** [comment]
My suggestion is to continue what we already have, just modify the docker build to copy static files instead of building the current vie project.

The current setup is the develop branch for dev, master (or tags) for production.

**Comment by pekrau** [comment]
Sounds good. You're right about using the dev branch for the dev machine, bad thinking on my part.

**Comment by ewels** [comment]
GitHub actions may be of interest for automated builds? Should be pretty easy with actions such as: https://github.com/peaceiris/actions-hugo

**Comment by ewels** [comment]
> just modify the docker build to copy static files instead of building the current vie project.

But we still need a `hugo` command somewhere to generate the HTML, right? Where would this be?

**Comment by talavis** [comment]
After quickly checking the documentation for Hugo, I'm guessing that something similar to the below Dockerfile should work:
```
FROM ubuntu:20.04 as build

RUN apt install hugo

COPY . /code
WORKDIR /code

RUN hugo -D

FROM nginx:alpine

COPY --from=build /code/public/ /usr/share/nginx/html/

EXPOSE 80
```

**Comment by talavis** [comment]
We have the dev page active on the [cluster](https://covid-portal-dev.dckube.scilifelab.se/), automated container generation on [dockerhub](https://hub.docker.com/repository/docker/scilifelabdatacentre/covid-hub/) for `develop` and `production`, and manual deployment to k8s. I think we can close this one?
