### ISSUE TITLE
URLs to EMBL sequence archive changed

### ISSUE THREAD

**Issue by johanrung** [ScilifelabDataCentre/covid-portal#246]
On https://covid19dataportal.se/data_types/genomics_transcriptomics/data/ ,  the page contains direct links the EU portal under the section "Data available on the European COVID-19 Data Portal". Their portal changed their URLs, so please update our portal accordingly:

https://www.covid19dataportal.org/sequences?db=embl -> https://www.covid19dataportal.org/sequences?db=embl-covid19

Possibly, this concerns other links in the portal too using db=embl which should now be db=embl-covid19.

**Comment by akochari** [comment]
The link appeared in 2 places. Both now fixed.
