### ISSUE TITLE
Structure content

### ISSUE THREAD

**Issue by viklund** [ScilifelabDataCentre/covid-portal#4]
I'm just thinking "out loud" here, please comment or start implement something.

I imagine one can use the Bulma tiles in a 2x2 grid and have each tile some specific information type, possibly expandable.

Like one tile for where to turn for support, one tile that links to european efforts, and so forth.

Or one could also imagine that the different tiles are geared to different potential users of the portal. Tiles could then for example be:

* I want to share my data
* I want support
* I want information about scilifelab/europena/worldwide covid19 efforts
* I want resources I can use

Some experimentation is needed to figure this out.

**Comment by talavis** [comment]
I believe more in the "I want..." approach.
So the page would be something like:
```
TItle
Some general info
-----------------------------------------------------
| I want to access data      | I want to share data |
-----------------------------------------------------
| About the covid-19 efforts | I want support       |
-----------------------------------------------------
Footer
```

**Comment by pekrau** [comment]
Johan had the idea that we should be inspired by EBI's Covid19 portal https://www.covid19dataportal.org/ . We can follow their overall structure, although not their exact theme, obviously.
