### ISSUE TITLE
Add "Text data" to data section

### ISSUE THREAD

**Issue by SonjaAits** [ScilifelabDataCentre/covid-portal#57]
Please add a section for "text data" under data types and include the following: 

COVID-19 publications on EuropePMC
[https://www.covid19dataportal.org/literature?db=literature](url)

COVID-19 Open Research Dataset (CORD-19)
CORD-19 is a growing collection of more than 128,000 scholarly articles about SARS-CoV-2 and other coronaviruses, which is put together by the Allen Institute for AI. 
[https://www.semanticscholar.org/cord19/download](url)

**Comment by ewels** [comment]
@talavis - I'm not sure this is fully solved yet? The issue auto-closed because of the merge, but will reopen for now.

**Comment by talavis** [comment]
According to the discussion we had on Slack this "morning", this should be solved in the intended way now. The way I understood is that Sonja will add links herself, while we created the sections (also "service" instead of data type).
