### ISSUE TITLE
Change section title "public health data"

### ISSUE THREAD

**Issue by johanrung** [ScilifelabDataCentre/covid-portal#60]
Please change the section title "Public Health Data" to "Health registry data" and keep only the RUT link in this section. In Swedish, the title should be "Registerdata".

**Comment by ewels** [comment]
Is there a plan to have other pages there in the future? Otherwise I recommend removing the page hierarchy for RUT. That is, make  `public_health_data/_index.md` the RUT page and remove `rut.md`. Otherwise we are adding additional clicks for no reason.

**Comment by johanrung** [comment]
We don't know yet, but it's likely to come other data from health registers and researchers coming from healthcare side - not sure if "register data" is perfect, and for now we only have RUT but there may be other things like biobank information and similar. 

"Public health data" is quite particularly the situation in the country with numbers of people infected or hospitalized and we will never really have that data. I want to make sure people don't expect the portal to be the major frontend or dashboard like the FHM or Johns Hopkins' sites - focus is on research data really. "Health data" is also complicated because it's not apparent how we will ever really be able to serve it. So I am a bit uncertain how to handle it, and not sure what to. expect when it comes to future content.

**Comment by ewels** [comment]
Ok - how about we just make it RUT then, solves the question of the generic title? We can always revert this in the future if we want more pages.

**Comment by talavis** [comment]
Is this what we want?

![image](https://user-images.githubusercontent.com/310966/82891207-a5222d00-9f4d-11ea-9aa5-fb8e590dc07a.png)

**Comment by ewels** [comment]
Yeah exactly - will now work as a direct link instead of a dropdown (and no empty page when linked to from the top navigation).

Not sure if a different name would be appropriate is the only thing, I'm not sure how many people will know what _Register utiliser tool_ really means (I don't).

**Comment by talavis** [comment]
@johanrung Any suggestions for title for the section? And also: who will fill it with text?

**Comment by johanrung** [comment]
I've asked VR for content. If I don't hear from them by noon tomorrow, we'll decide something to do as a placeholder. Per suggested "Public Health Statistics" which I think is a better term and I think even with input from VR, the title could be "Public Health Statistics".

**Comment by talavis** [comment]
Any updates?
