### ISSUE TITLE
"Avbildningsdata" -> "Bilddata"

### ISSUE THREAD

**Issue by johanrung** [ScilifelabDataCentre/covid-portal#62]
The title of the section "Avbildningsdata" (Swedish version of "Imaging data") should be "Bilddata".

**Comment by talavis** [comment]
Are you sure about that one? I don't have any specific standard for "Imaging data", but the official translations in MESH usually use "avbildning", e.g.:

* Molecular Imaging -> Molekylär avbildning [link](https://mesh.kib.ki.se/term/D057054/molecular-imaging)
* Optical Imaging -> Optisk avbildning [link](https://mesh.kib.ki.se/term/D061848/optical-imaging)
* Perfusion Imaging -> Perfusionsavbildning [link](https://mesh.kib.ki.se/term/D055420/perfusion-imaging)
* Radionuclide Imaging -> Radionuklidavbildning [link](https://mesh.kib.ki.se/term/D011877/radionuclide-imaging)

The only exceptions I could find are where the methods have specific names in Swedish and `Diagnostic Imaging` (Bilddiagnostik [link](https://mesh.kib.ki.se/term/D003952/diagnostic-imaging))

**Comment by johanrung** [comment]
Yes I am sure. I don't think those terms are well established by people in the field. We talk about "bildanalys", "bildverktyg", "bildbehandling" etc.

Google fight: "bilddata" -> 72,600 hits. "Avbildningsdata" -> 987 hits.

**Comment by talavis** [comment]
Ok. I also thing "bilddata" sounds better, but I became a bit doubtful when I saw that the majority of the translated MESH terms used "avbildning". Will fix it.
