### ISSUE TITLE
Add text about SND

### ISSUE THREAD

**Issue by pekrau** [ScilifelabDataCentre/covid-portal#91]
Swedish National Data Service (SND)

Swedish National Data Service has a primary function to support the accessibility, preservation, and re-use of research data and related materials. As a national infrastructure, SND coordinates a network of more than 30 universities and public research institutes in Sweden. SND is certified data repository and provides services for researchers to share and access research data from all research areas.

Read more on SND’s website (https://snd.gu.se/en)

(@pekrau will look at this)

**Comment by akochari** [comment]
Done.
