### ISSUE TITLE
Clarify whether data in swedish side is available on european side

### ISSUE THREAD

**Issue by pekrau** [ScilifelabDataCentre/covid-portal#96]
From VR reviewer:

Snygg och tydlig sida, bra med tydlig kontaktinformation och text som uppmuntrar deponering av data och erbjuder hjälp med det. Jag har lite svårt att greppa om allt på den svenska sida också kommer att gå att hitta på den europeiska eller hur uppdelningen görs? Är tanken att man börjar leta på den svenska sidan och sedan ev söker sig till den europeiska om man inte hittar det man söker?

**Comment by akochari** [comment]
It is available in the Partners section (https://www.covid19dataportal.org/partners), linked from the top of each page.
