### ISSUE TITLE
Clarify and/or add content to Resource page

### ISSUE THREAD

**Issue by pekrau** [ScilifelabDataCentre/covid-portal#98]
From VR reviewer:

Jag greppar nog inte heller direkt vad som är tänkt att listas under Resources. För structural data står bara en prediktionssida för proteinstrukturer och fragmentscreeningsdata. Oklart för mig vad tanken är med just dessa två eller vilken typ av resurser som är planerade att vara med.

**Comment by akochari** [comment]
Probably not relevant anymore. Moreover, page will be updated shortly with new links, improved structure.
